[program:control]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 30 && exec python3 /home/user/foxtel_watcher/launch.py"
autostart=true
autorestart=true
restartPause=30

stdout_logfile=/home/user/foxtel_watcher/control.log
stderr_logfile=/home/user/foxtel_watcher/control.log

[program:control_log_viewer]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 32 && exec gnome-terminal --wait --title='Control Log' -- bash -c 'tail -f /home/user/foxtel_watcher/control.log; exec bash'"
autostart=true
autorestart=true
restartPause=30
