
[program:control]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 20 && exec python3 /home/user/foxtel_watcher/launch.py"
autostart=true
autorestart=true


stdout_logfile=/home/user/foxtel_watcher/control.log
stderr_logfile=/home/user/foxtel_watcher/control.log

[program:control_log_viewer]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 22 && exec xterm -T 'Control Log' -fa 'Monospace' -fs 14 -geometry 140x40 -e tail -F /home/user/foxtel_watcher/control.log"
autostart=true
autorestart=true

