[program:player]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user

command=bash -c "sleep 20 && exec google-chrome --remote-debugging-port=9222 --hide-crash-restore-bubble --user-data-dir=/home/user/foxtel_watcher/ChromeProfile"

autostart=true
autorestart=true
restartPause=20

stdout_logfile=/home/user/foxtel_watcher/player.log
stderr_logfile=/home/user/foxtel_watcher/player.log


[program:player_log_viewer]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 32 && exec gnome-terminal --wait --title='Player Log' -- bash -c 'tail -f /home/user/foxtel_watcher/player.log; exec bash'"
autostart=true
autorestart=true
restartPause=30
