
[program:controller]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 20 && exec python3 /home/user/foxtel_watcher/controller.py"
autostart=true
autorestart=true


stdout_logfile=/home/user/foxtel_watcher/controller.log
stderr_logfile=/home/user/foxtel_watcher/controller.log

[program:controller_log_viewer]
environment=
	DISPLAY=:0,
	XDG_RUNTIME_DIR=/run/user/1000,
	HOME="/home/user",
	USER="user"

user=user
command=bash -c "sleep 22 && exec xterm -T 'Controller Log' -fa 'Monospace' -fs 14 -geometry 140x40 -e tail -F /home/user/foxtel_watcher/controller.log"
autostart=true
autorestart=true

